src/Entity/Category.php
<?php

namespace App\Entity;

use App\Repository\CategoryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=CategoryRepository::class)
 */
#[UniqueEntity(
    fields: ['slug'],
    errorPath: 'slug',
    message: 'Ce slug est deja utilisé',
)]
#[UniqueEntity(
    fields: ['name'],
    errorPath: 'name',
    message: 'Ce nom est deja utilisé',
)]
class Category
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255,unique=true)
     */
    #[Assert\NotBlank(message: 'Veuillez renseigner un Nom')]
    #[Assert\Length(max: 255, maxMessage: 'Le nom de votre categorie est trop long')]
    private $name;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\OneToMany(targetEntity=Category::class, mappedBy="category_parent" )
     */
    private $categories_children;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="categories_childrens")
     */
    private $category_parent;

    /**
     * @ORM\OneToMany(targetEntity=Produit::class, mappedBy="category")
     */
    private $produits;

    /**
     * @ORM\OneToOne(targetEntity=Picture::class, cascade={"persist", "remove"})
     */
    private $picture;

    #[Assert\Image(mimeTypes: ["image/jpeg", "image/png", "image/gif", "image/jpg"])]
    private $pictureFile;

    /**
     * @ORM\Column(type="string", length=255, unique=true ,nullable=false)
     */
    #[Assert\NotBlank(message: 'Veuillez rajoutez un slug')]
    #[Assert\Regex(pattern: '/^[a-z0-9]+(?:-[a-z0-9]+)*$/', message: "Le slug n'a pas le bon format")]
    private $slug;



    /**
     * @ORM\ManyToMany(targetEntity=BandeCategoryTitle::class, mappedBy="categories")
     */
    private $bandesTitle;

    /**
     * @ORM\ManyToMany(targetEntity=BandeCategory::class, mappedBy="categories")
     */
    private $bandesSimple;

    public function getId(): ?int
    {
        return $this->id;
    }
    public function __construct()
    {
        $this->categories_children = new ArrayCollection();
        $this->produits = new ArrayCollection();
        $this->bandesSimple = new ArrayCollection();
        $this->bandesTitle = new ArrayCollection();
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCategoryParent(): ?self
    {
        return $this->category_parent;
    }

    public function setCategoryParent(?self $category_parent): self
    {
        $this->category_parent = $category_parent;

        return $this;
    }

    /**
     * @return Collection|self[]
     */
    public function getCategoriesChildrens(): Collection
    {
        return $this->categories_children;
    }

    public function addCategorie(self $categorie): self
    {
        if (!$this->categories_children->contains($categorie)) {
            $this->categories_children[] = $categorie;
            $categorie->setCategoryParent($this);
        }

        return $this;
    }

    public function removeCategorie(self $categorie): self
    {
        if ($this->categories_children->removeElement($categorie)) {
            // set the owning side to null (unless already changed)
            if ($categorie->getCategoryParent() === $this) {
                $categorie->setCategoryParent(null);
            }
        }
        return $this;
    }

    /**
     * @return Collection|Produit[]
     */
    public function getProduits(): Collection
    {
        return $this->produits;
    }

    public function getProduitsAfficher()
    {
        $produits = $this->produits;
        $newArray = [];
        foreach ($produits as $produit) {
            if ($produit->getAfficher()) {
                array_push($newArray, $produit);
            }
        }
        return $newArray;
    }
    public function addProduit(Produit $produit): self
    {
        if (!$this->produits->contains($produit)) {
            $this->produits[] = $produit;
            $produit->setCategory($this);
        }

        return $this;
    }

    public function removeProduit(Produit $produit): self
    {
        if ($this->produits->removeElement($produit)) {
            // set the owning side to null (unless already changed)
            if ($produit->getCategory() === $this) {
                $produit->setCategory(null);
            }
        }

        return $this;
    }

    public function getPicture(): ?Picture
    {
        return $this->picture;
    }

    public function setPicture(?Picture $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    /**
     * Get the value of pictureFile
     */
    public function getPictureFile()
    {
        return $this->pictureFile;
    }

    /**
     * Set the value of pictureFile
     *
     * @return  self
     */
    public function setPictureFile($pictureFile)
    {
        if ($pictureFile) {
            $picture = new Picture();
            $picture->setImageFile($pictureFile);
            $this->picture = $picture;
        }

        $this->pictureFile = $pictureFile;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|BandeCategory[]
     */
    public function getBandesSimple(): ?Collection
    {
        return $this->bandesSimple;
    }

    public function addBandeSimple(BandeCategory $bandeCategory): self
    {
        if (!$this->bandesSimple->contains($bandeCategory)) {
            $this->bandesSimple = $bandeCategory;
            $bandeCategory->addCategory($this);
        }

        return $this;
    }

    public function removeBandeSimple(BandeCategory $bandeCategory): self
    {
        if ($this->bandesSimple->removeElement($bandeCategory)) {
            $bandeCategory->removeCategory($this);
        }

        return $this;
    }
    /**
     * @return Collection|BandeCategoryTitle[]
     */
    public function getBandesTitle(): ?Collection
    {
        return $this->bandesTitle;
    }

    public function addBande(BandeCategoryTitle $bandeCategoryTitle): self
    {
        if (!$this->bandesTitle->contains($bandeCategoryTitle)) {
            $this->bandesTitle = $bandeCategoryTitle;
            $bandeCategoryTitle->addCategory($this);
        }
        return $this;
    }

    public function removeBande(BandeCategoryTitle $bandeCategoryTitle): self
    {
        if ($this->bandesTitle->removeElement($bandeCategoryTitle)) {
            $bandeCategoryTitle->removeCategory($this);
        }

        return $this;
    }

    public function getBandes()
    {
      
     
        return  array_merge($this->bandesTitle->toArray(), $this->bandesSimple->toArray());
    }

    public function doYouHaveCategoriesWhoHaveProduct()
    {
        $categoriesChildren = $this->getCategoriesChildrens();
        foreach ($categoriesChildren as $categoryChildren) {
            if ($categoryChildren->doYouHaveProductsWhoHaveAfficher()) {
                return true;
            }
        }
        return false;
    }

    public function doYouHaveProductsWhoHaveAfficher()
    {
        $products = $this->getProduits();
        foreach ($products as $product) {
            if ($product->getAfficher()) {
                return true;
            }
        }
        return false;
    }
}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Produit;
use App\Repository\ProduitRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

use Exception;
use Symfony\Component\HttpFoundation\Request;


class ProductController extends AbstractController
{

    private $em;
    private $productRepo;


    function __construct(EntityManagerInterface $em, ProduitRepository $productRepo)
    {
        $this->em = $em;

        $this->productRepo = $productRepo;
    }
    #[Route('/produit/{slug}', name: 'produit')]
    public function index(Produit $product, ProduitRepository $produitRepo): Response
    {

        if (!$product->getAfficher()) {
            throw new Exception('Cette page n\'existe pas');
        }
        $productsAlike =  $produitRepo->findFourProductsDependsOnCategoryId($product->getCategory()->getId(), $product->getId());


        return $this->render('product/index.html.twig', [
            'product' => $product,
            'alikes' => $productsAlike
        ]);
    }
}

src/Controller/ProductsController.php
<?php

namespace App\Controller;

use App\Entity\Category;
use App\Entity\Marque;
use App\Repository\CategoryRepository;
use App\Repository\MarqueRepository;
use App\Repository\ProduitRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use PhpParser\Node\Expr\Cast\Array_;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ProductsController extends AbstractController
{


    private $em;
    private $productRepo;


    function __construct(EntityManagerInterface $em, ProduitRepository $productRepo)
    {
        $this->em = $em;
        $this->productRepo = $productRepo;
    }
    public function xmlHttpRequestLoad($paginator, $categorySlug, $search, $marqueSlug, $order, $request)
    {
        $products = $this->productRepo->findProductsDependsOnParameters($categorySlug, $search, $marqueSlug, $order);
        $PaginateProducts = $paginator->paginate(
            $products,
            $request->query->getInt('page', 1),
            12,
        );
        return $this->render('products/productsList.html.twig', [
            'products' => $PaginateProducts,
        ]);
    }
    public function fillArrayMarquesAndCategories($productsGlobal, $marques, $categories)
    {
        foreach ($productsGlobal as $value) {
            if (is_array($marques)) {

                $marqueName = $value->getMarque() ? $value->getMarque()->getName() : "Sans Marque";
                if (isset($marques[$marqueName])) {
                    $marques[$marqueName]["nbr"] += 1;
                } else {
                    $marques[$marqueName] = array(
                        "nbr" => 1,
                        "slug" => $value->getMarque() ? $value->getMarque()->getSlug() : "Sans_Marque"
                    );
                }
            }
            if (is_array($categories)) {
                $categoryName = $value->getCategory()->getName();
                if (isset($categories[$categoryName])) {
                    $categories[$categoryName]["nbr"] += 1;
                } else {
                    $categories[$categoryName] = array(
                        "nbr" => 1,
                        "slug" => $value->getCategory()->getSlug()
                    );
                }
            }
        }
        return [$marques, $categories];
    }


    public function howManyActiveFilter($categorySlug, $marqueSlug)
    {
    }

    #[Route('/produits/recherche/{q}', name: 'productsSearch')]
    public function search($q, PaginatorInterface $paginator, Request $request): Response
    {
        $marqueSlugData = $request->query->get("marque") ? $request->query->get("marque") : "none";
        $order = $request->query->get("order");
        $search = $q;
        $category = null;
        $marque = null;
        if ($marqueSlugData == 'Sans_Marque') {
            $marqueSlug = null;
        } else {
            $marqueSlug = $marqueSlugData;
        }
        $categorySlug  = $request->query->get("categorie");
        if ($request->isXmlHttpRequest()) {
            return $this->xmlHttpRequestLoad($paginator, $categorySlug, $search, $marqueSlug, $order, $request);
        }
        $activeFilter = 0;
        if ($categorySlug) {
            $activeFilter += 1;
        }
        if ($marqueSlug != "none") {
            $activeFilter += 1;
        }
        $productsGlobal = $this->productRepo->findProductsDependsOnSearch($search, $order);
        if ($categorySlug || $marqueSlug != "none") {

            $products = $this->productRepo->findProductsDependsOnParameters($categorySlug, $search, $marqueSlug, $order);
        } else {
            $products = $productsGlobal;
        }

        $PaginateProducts = $paginator->paginate(
            $products,
            $request->query->getInt('page', 1),
            12,
        );
        [$marques, $categories] = $this->fillArrayMarquesAndCategories($productsGlobal, [], []);
        return $this->render('products/index.html.twig', [
            'activeFilter' => $activeFilter,
            'products' => $PaginateProducts,
            'marques' => $marques,
            'categories' => $categories,
            "category" => $category,
            "search" => $q,
            "marque" => $marque,
            "marqueSlug" => $marqueSlugData,
            "categorySlug" => $categorySlug,
            "order" => $order
        ]);
    }


    #[Route('/produits/marque/{slug}', name: 'productsMarques')]
    public function marque(Marque $marque, PaginatorInterface $paginator, Request $request, MarqueRepository $marqueRepos, CategoryRepository $categoryRepo): Response
    {
        $categorySlug  = $request->query->get("categorie");
        $order = $request->query->get("order");
        $marqueSlug = $marque->getSlug();
        $search = null;
        $category = null;
        if ($request->isXmlHttpRequest()) {
            return $this->xmlHttpRequestLoad($paginator, $categorySlug, $search, $marqueSlug, $order, $request);
        }

        $activeFilter = 0;
        if ($categorySlug) {
            $activeFilter += 1;
        }

        $productsGlobal = $this->productRepo->findProductsDependsOnMarqueSlug($marqueSlug, $order);

        if ($categorySlug) {
            $products = $this->productRepo->findProductsDependsOnParameters($categorySlug, $search, $marqueSlug, $order);
        } else {
            $products = $productsGlobal;
        }
        $PaginateProducts = $paginator->paginate(
            $products,
            $request->query->getInt('page', 1),
            12,
        );
        [$marques, $categories] = $this->fillArrayMarquesAndCategories($productsGlobal, null, []);
        return $this->render('products/index.html.twig', [
            'activeFilter' => $activeFilter,
            'products' => $PaginateProducts,
            'marques' => $marques,
            'categories' => $categories,
            "category" => $category,
            "search" => $search,
            "marque" => $marque,
            "marqueSlug" => null,
            "categorySlug" => $categorySlug,
            "order" => $order
        ]);
    }
    #[Route('/produits/categorie/{slug}', name: 'productsCategories')]
    public function index(Category $category, PaginatorInterface $paginator, Request $request, MarqueRepository $marqueRepos, CategoryRepository $categoryRepo): Response
    {
        $marqueSlugData = $request->query->get("marque") ? $request->query->get("marque") : "none";
        $order = $request->query->get("order");
        $search = null;
        if ($marqueSlugData == 'Sans_Marque') {
            $marqueSlug = null;
        } else {
            $marqueSlug = $marqueSlugData;
        }
        $categorySlug  = $category->getSlug();
        if ($request->isXmlHttpRequest()) {
            return $this->xmlHttpRequestLoad($paginator, $categorySlug, $search, $marqueSlug, $order, $request);
        }

        $activeFilter = 0;

        if ($marqueSlug != "none") {
            $activeFilter += 1;
        }
        $productsGlobal = $this->productRepo->findProductsDependsOnCategorySlug($categorySlug, $order);
        if ($marqueSlug != "none") {
            $products = $this->productRepo->findProductsDependsOnParameters($categorySlug, $search, $marqueSlug, $order);
        } else {
            $products = $productsGlobal;
        }
        $PaginateProducts = $paginator->paginate(
            $products,
            $request->query->getInt('page', 1),
            12,
        );


        [$marques, $categories] = $this->fillArrayMarquesAndCategories($productsGlobal, [], null);
        return $this->render('products/index.html.twig', [
            'activeFilter' => $activeFilter,
            'products' => $PaginateProducts,
            'marques' => $marques,
            'categories' => $categories,
            "category" => $category,
            "search" => null,
            "marque" => null,
            "marqueSlug" => $marqueSlugData,
            "categorySlug" => null,
            "order" => $order
        ]);
    }
}

templates/products/index.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
	{{ parent() }}
	{{ encore_entry_link_tags('products') }}
{% endblock %}

{% block cdn %}
	{{ parent() }}
	<script src="https://code.jquery.com/jquery-3.6.0.slim.min.js" integrity="sha256-u7e5khyithlIdTpu22PHhENmPcRdFiHRjhAuHcs05RI=" crossorigin="anonymous"></script>

{% endblock %}

{% block title %}
	Nos produits -
	{% if category %}
		{{category.name}}
	{% endif %}

	{% if marque %}
		{{marque.name|capitalize}}

	{% endif %}

	{% if search %}
		«{{search|capitalize}}»

	{% endif %}

{% endblock %}

{% block body %}
	<div class="content-produits flex column ">
		<div class="up-produits flex column ">
			<div class=" linkss flex">

				{% if category %}
					<a style="color: {{colors.allColors.primary}}" href="{{path('home')}}">Accueil</a>

					<span>
						></span>
					<a style="color: {{colors.allColors.primary}}" href="{{path('category',{ slug : category.categoryParent.slug })}}">{{category.categoryParent.name}}</a>
					<span>
						></span>
					<p>{{category.name}}</p>

				{% endif %}
				{% if marque %}
					<div class="marqueTop">
						<img width="30%" height="70%" src="{{ vich_uploader_asset(marque.picture,'imageFile') }}" alt="">
						<h1>{{marque.name|capitalize}}</h1>
						<p>{{marque.description}}</p>

					</div>

				{% endif %}


			</div>
			{% if category %}
				<h1>{{category.name}}</h1>


			{% endif %}
			{% if search %}
				<div class="search">
					<span>«{{search|capitalize}}»</span>
					{% if products.getTotalItemCount > 1 %}
						{{products.getTotalItemCount}}
						produits trouvés

					{% elseif products.getTotalItemCount == 1 %}

						{{products.getTotalItemCount}}
						produit trouvé
					{% else %}
						Aucun produit trouvé


					{% endif %}


				</div>

			{% endif %}


			<div class="flex tri">
				<p>Trier par
				</p>
				<select onchange="newTri(this)">
					<option value="Pertinence">Pertinence</option>
					<option {{order == "ASC" ? "selected" : ""}} value="ASC">Nom produit acroissant</option>
<option {{order == "DESC" ? "selected" : ""}} value="DESC">Nom produit decroissant</option>

				</select>

			</div>
		</div>

		<div class="down-produits flex">
			<div class="left-produits flex column ">
				<div class=" tri-coulissant  flex column">
					<div class=" tri-haut inactive flex">


						<div style="--background: {{colors.allColors.primary}};" class=" filtre  flex">

							<span class="{{activeFilter > 0 ? "active" : "" }}">{{activeFilter}}</span>filtre actif
						</div>


					</div>


				</div>
				{% if marques %}
					<div class=" tri-coulissant flex column">
						<div onclick="getTheTri(this)" class=" tri-haut flex">

							<p>Marque</p>
							<span>
								<i class="fas fa-arrow-down"></i>
							</span>

						</div>
						<div class="tri-bas column ">
							{% for marqueName,key in marques %}
								<span data-slug={{key.slug}} class="flex">

									<input {{marqueSlug == key.slug ? "checked" : ""}} onclick="adaptMark(this)" type="checkbox" name="stay" placeholder="hoelndelnk">
									{{marqueName|capitalize}}

									({{key.nbr}})


								</span>

							{% endfor %}


						</div>


					</div>
				{% endif %}
				{% if categories %}

					<div class=" tri-coulissant flex column">
						<div onclick="getTheTri(this)" class=" tri-haut flex">

							<p>Categorie</p>
							<span>
								<i class="fas fa-arrow-down"></i>
							</span>

						</div>
						<div class="tri-bas column ">
							{% for categoryName,key in categories %}
								<span data-slug={{key.slug}} class="flex">
									<input {{categorySlug == key.slug ? "checked" : ""}} onclick="adaptCategory(this)" type="checkbox" name="stay" placeholder="hoelndelnk">

									{{categoryName|capitalize}}


									({{key.nbr}})


								</span>

							{% endfor %}


						</div>
					</div>
				{% endif %}


			</div>
			<div class="right-produits flex column">

				{{ include('products/productsList.html.twig') }}
			</div>


		</div>


	</div>
{% endblock %}
{% block javascripts %}
	{{ parent() }}
	{{ encore_entry_script_tags('products') }}
	{{ encore_entry_script_tags('addbasket') }}
	{{ encore_entry_script_tags('produitQuery') }}
{% endblock %}

templates/products/productsList.html.twig
<div class="right-produits-haut flex">
	{% for product in products %}

		<div class="produit flex column">
			<a href="{{path('produit',{ slug: product.slug })}}">

				<div class="img-produit">
					<img width="60%" height="95%" src="{{ vich_uploader_asset(product.pictures[0],'imageFile') }}" alt="">

				</div>
				<div class="titre-produit">
					<h3>{{product.name|capitalize}}</h3>

				</div>
				<div class="reference-produit">
					<h3>{{product.reference}}</h3>
				</div>
			</a>
			<div class="bas-produit flex column ">
				<div class="disponible flex column ">
					<h2>Disponibilité :
					</h2>
<h2>{{product.disponibilite}}</h2>

				</div>
				<div class="ajout-produit flex">
					<div class="flex surquantity column">
						<div class="quantity flex">
							<input readonly="readonly" type="number" name="tentacles" min="1" value="1">

						</div>
						<div class="unite">
							{{product.unite}}
						</div>
					</div>
<button style="background-color: {{colors.allColors.primary}}" data-name={{product.name}} data-id={{ product.id }} {{ is_granted('ROLE_USER') ? 'onclick="addBasket(this)"' : 'onclick="popup(`Vous devez vous connecter pour pouvoir ajoutez un produit dans votre panier`,`error`)"'}}>Ajoutez</button>



				</div>

			</div>
		</div>

	{% endfor %}


</div>
<div style="--background: {{colors.allColors.primary}};" class="righ-produits-bas flex column">


	{{ knp_pagination_render(products) }}

</div>